### PR TITLE
Update with newer ndx-template version 

### PR DESCRIPTION
**Pull request by alessandratrapani**
Update with newer ndx-template version as suggested in #23

### CODE REVIEW

**Comment by rly** [comment]
I get a slightly different error when I try to reproduce this locally:
```
________________________________________________________ ERROR collecting src/pynwb/tests/test_constructors.py _________________________________________________________
src/pynwb/tests/test_constructors.py:7: in <module>
    from ndx_microscopy.testing import (
src/pynwb/ndx_microscopy/__init__.py:25: in <module>
    ExcitationLightPath = get_class("ExcitationLightPath", extension_name)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/utils.py:672: in func_call
    return func(**pargs)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/pynwb/__init__.py:260: in get_class
    return __TYPE_MAP.get_dt_container_cls(neurodata_type, namespace)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/utils.py:668: in func_call
    return func(args[0], **pargs)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/build/manager.py:537: in get_dt_container_cls
    spec = self.__ns_catalog.get_spec(namespace, data_type)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/utils.py:668: in func_call
    return func(args[0], **pargs)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/spec/namespace.py:316: in get_spec
    return self.__namespaces[namespace].get_spec(data_type)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/utils.py:668: in func_call
    return func(args[0], **pargs)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/spec/namespace.py:150: in get_spec
    raise ValueError("No specification for '%s' in namespace '%s'" % (data_type, self.name))
E   ValueError: No specification for 'ExcitationLightPath' in namespace 'ndx-microscopy'
__________________________________________________________ ERROR collecting src/pynwb/tests/test_roundtrip.py __________________________________________________________
src/pynwb/tests/test_roundtrip.py:8: in <module>
    from ndx_microscopy.testing import (
src/pynwb/ndx_microscopy/__init__.py:25: in <module>
    ExcitationLightPath = get_class("ExcitationLightPath", extension_name)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/utils.py:672: in func_call
    return func(**pargs)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/pynwb/__init__.py:260: in get_class
    return __TYPE_MAP.get_dt_container_cls(neurodata_type, namespace)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/utils.py:668: in func_call
    return func(args[0], **pargs)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/build/manager.py:537: in get_dt_container_cls
    spec = self.__ns_catalog.get_spec(namespace, data_type)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/utils.py:668: in func_call
    return func(args[0], **pargs)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/spec/namespace.py:316: in get_spec
    return self.__namespaces[namespace].get_spec(data_type)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/utils.py:668: in func_call
    return func(args[0], **pargs)
../../../miniconda3/envs/test2/lib/python3.12/site-packages/hdmf/spec/namespace.py:150: in get_spec
    raise ValueError("No specification for '%s' in namespace '%s'" % (data_type, self.name))
E   ValueError: No specification for 'ExcitationLightPath' in namespace 'ndx-microscopy'
```

I will investigate today and get back to you.

**Comment by rly** [comment]
I deleted the repo and re-cloned it, and now I get the same error. Interesting. Something must have been cached strangely.

**Comment by rly** [comment]
OK I resolved the issue. `ndx_ophys_devices` needs to be imported before loading the namespace for `ndx-microscopy` because within `ndx_ophys_devices/__init__.py`, the `ndx-ophys-devices` namespace is loaded into the global type map, and that namespace needs to exist in the type map when loading `ndx-microscopy` into the global type map.

**Comment by alessandratrapani** [comment]
Thank you so much @rly . I will merge this PR, and continuing debugging on #22

**Pull request merged**
